name: upload-artifact

on: [push]

jobs:
  steps:
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: workflows
	path: ./python_3_8.txt ./python_3_9.txt ./python_3_10.txt